gsettings set org.cinnamon.desktop.background picture-uri 'file:///usr/share/backgrounds/gnome/truchet-l.jpg'
gsettings set org.cinnamon.theme name 'Arc-Dark'
gsettings set org.cinnamon.desktop.wm.preferences theme 'Arc-Dark'
gsettings set org.cinnamon.desktop.interface icon-theme 'Arc'
gsettings set org.cinnamon.desktop.interface gtk-theme 'Arc-Dark'
gsettings set org.cinnamon.desktop.interface cursor-theme 'OpenZone_White'
gsettings set org.cinnamon.desktop.applications.terminal exec 'kitty'
